### ISSUE TITLE
Addon not installing on Kodi 16.1

### ISSUE THREAD

**Issue by malua** [Frolanta/youtube-kodi-webinterface#1]
Do you have any idea on why the add-on won't install on on kodi 16.1?

I'll provide a log later.

Thank you in advance!

**Comment by Frolanta** [comment]
I just tried on a fresh Kodi install (on my windows desktop) since i'm on 1.5 or something on my raspberry.

But I didn't get any issue.

(Stupid question) Are you sure you tried to install "webinterface.ywifk.0.2.0.zip" and not the all repo ?

**Comment by malua** [comment]
Ok, sry for the issue, i got it working. The Problem is when I download the file "webinterface.ywifk.0.2.0.zip" it's not a valid zip file. Now I downloaded the whole repo and extracted the zip file and it works fine. Thanks!

**Comment by Frolanta** [comment]
Great, if you have any other issue regarding the installation (editing the .js file, ...) I'm here to help.
I should add this in the Readme but you have to enable **Remote Control** in the settings.
